### ISSUE TITLE
PyInstaller packing into Linux/macOS on Windows

### ISSUE THREAD

**Issue by pwyq** [WarshipGirls/WGViewer#93]

**Comment by pwyq** [comment]
Ok, based on my search, an OS's app can only be packed on its own machine.
To pack cross-platform, we have to use docker.

[src](https://blog.halukshan.com/blog/2020/03/06/pyinstaller-generate-win-exe-on-linux/)

**Comment by pwyq** [comment]
blocked by https://github.com/cdrx/docker-pyinstaller/issues/86

**Comment by pwyq** [comment]
```
pwyq@pwyq-R7:~/github/WarshipGirls$ sudo docker run -v "$(pwd):/src/" cdrx/pyinstaller-windows
[sudo] password for pwyq: 

701 INFO: PyInstaller: 3.6
701 INFO: Python: 3.7.5
701 INFO: Platform: Windows-7-6.1.7601-SP1
712 INFO: UPX is not available.
713 INFO: Removing temporary files and cleaning cache in C:\users\root\Application Data\pyinstaller
Traceback (most recent call last):
  File "c:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\Python37\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\Python37\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\Python37\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\Python37\lib\site-packages\PyInstaller\building\build_main.py", line 636, in build
    os.makedirs(pth)
  File "c:\Python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] Invalid name: '/tmp\\*'

```

**Comment by pwyq** [comment]
Today I tried to run on my ubuntu, but it was blocked by disk size. could not fix. Maybe need to reinstall ubuntu OS
